Fancy output test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,7 +64,49 @@ runs:
       shell: bash
       run: |
         cd ${{ github.action_path }}
-        CONFIG=$(lua5.3 ${{ github.action_path }}/config.lua "${{ inputs.config }}" '${{ inputs.title }}' '${{ inputs.type }}' '${{ inputs.tag1 }}' '${{ inputs.tag2 }}' '${{ inputs.tag3 }}')
+
+        # Use a subshell to capture both output and exit status
+        CONFIG_OUTPUT=$(lua5.3 ${{ github.action_path }}/config.lua \
+            "${{ inputs.config }}" \
+            '${{ inputs.title }}' \
+            '${{ inputs.type }}' \
+            '${{ inputs.tag1 }}' \
+            '${{ inputs.tag2 }}' \
+            '${{ inputs.tag3 }}' 2>&1; echo $?)
+
+        # Extract exit status
+        CONFIG_EXIT_STATUS=${CONFIG_OUTPUT##*$'\n'}
+
+        # Handle a nonzero exit code as a lua error
+        if [ "$CONFIG_EXIT_STATUS" -ne 0 ]; then
+            if [[ $CONFIG_OUTPUT =~ .*/(.*\.lua):([0-9]+):(.*) ]]; then
+                FILE_NAME="${BASH_REMATCH[1]}"
+                LINE_NUMBER="${BASH_REMATCH[2]}"
+                ERROR_MESSAGE="${BASH_REMATCH[3]}"
+
+                # Format the error message for GitHub Actions
+                echo "::error file=${FILE_NAME},line=${LINE_NUMBER}::${ERROR_MESSAGE}"
+            fi
+
+            SUMMARY=$(cat <<EOF
+            ## :x: Failed to generate an addon.json!
+
+            ### Error
+            ```
+            $CONFIG_OUTPUT
+            ```
+            EOF
+            )
+
+            echo "$SUMMARY" >> "$GITHUB_STEP_SUMMARY"
+
+            exit 1
+        fi
+
+        # Remove the exit status from the output
+        CONFIG=$(echo "$CONFIG_OUTPUT" | head -n -1)
+
+        # Set the path of the addon json in the local environment
         echo "config_file=$CONFIG" >> "$GITHUB_ENV"
 
     - name: Run gma packer
